export const AppStrings = {
  USERNAME_EXISTS: "username is already exist.",
  EMAIL_EXISTS: "Email is already registered.",
  MOBILE_EXISTS: "Mobile No is already exist.",
  USERNAME_NOT_EXISTS: "username does not exist.",
  EMAIL_NOT_EXISTS: "Email does not exist.",
  MOBILE_NOT_EXISTS: "Mobile does not exist.",
  INVALID_PASSWORD: "Invalid password.",
  OLD_PASSWORD_INVALID: "Old password is wrong",
  BLACKLISTED_TOKEN: "blacklisted token.",
  INVALID_SESSION: "Your session is not valid.",
  INVALID_REQUEST: "Invalid request.",
  UNAUTHORIZED: "Full authentication is required to access this resource",
  INVALID_PAYLOAD: "Couldn't process data",
  USERNAME_EMAIL_MOBILE_REQUIRED: "username, email or mobile is required.",
  EMAIL_MOBILE_REQUIRED: "email or mobile is required.",
  DEVICE_REQUIRED: "device is required.",
  OTP_SENT: "OTP sent successfully.",
  USER_CREDENTIAL_DOES_NOT_MATCH: "User credentials do not match.",
  USER_DEACTIVATE: "Your account is Deactive please contact to Administrator.",
  DECRYPT_DATA_IS_REQUIRED: "Decrypt data is required.",
  USER_INACTIVE: "Your account is Inactive please activate your account.",
  LOGIN_DETAILS: "Login details not found.",

  ALREADY_ACCEPTED: "Already accepted",
  ALREADY_REJECTED: "Already rejected",

  SOMETHING_WRONG: "Somethig went wrong.",
  VERIFY_SUCCESS: "Verify successfully.",
  SECRET_INVALID: "Secret code invalid.",
  SENDER_ADMIN_NOT_FOUND: "Admin not found.",
  NOTIFICATION_UPDATED: "Notification read successfully.",

  OTP_TOKEN_REQUIRED: "OTP and token is required.",
  INVALID_OTP: "Invalid OTP.",
  INVALID_DEVICE: "Invalid device.",
  OTP_EXPIRED: "OTP expired.",
  OTP_VERIFIED: "OTP verified.",
  OTP_NOT_MATCH: "Please enter valid verification code.",
  OTP_ALREADY_VERIFIED: "OTP already verified.",
  OTP_REQUEST_LIMIT: "OTP request limit reached.",

  USER_NOT_FOUND: "User not found.",
  INVALID_TOKEN: "Invalid token.",
  TOKEN_EXPIRED: "Token expired.",

  VENDOR_NOT_FOUND: "Vendor not found.",

  SET_LOCATION: "Location not found.",

  PASSWORD_CHANGED: "Password changed successfully.",
  USERID_MISSING: "UserId is missing.",
  NO_OTP_FOUND: "No OTP found.",
  USER_TYPE_MISMATCH: "User type mismatch.",

  PROFILE_UPDATED: "Profile updated successfully.",

  IMAGE_DELETED: "Image deleted successfully.",
  IMAGE_UPLOADED: "Image uploaded successfully.",
  IMAGE_NOT_FOUND: "Image not found.",
  IMAGE_NOT_UPLOADED: "Image not uploaded.",

  AUDIO_NOT_FOUND: "Audio not found.",
  AUDIO_NOT_UPLOADED: "Audio not uploaded.",
  AUDIO_UPLOADED: "Audio uploaded successfully.",

  PROFILE_FETCHED: "Profile fetched successfully.",

  SERVER_ERROR: "Server error. Please try again later.",

  AGE_NOT_VALID: "Age must be greater than 15.",
  DOB_NOT_VALID: "DOB must be greater than 15 years ago.",

  EMAIL_REQUIRED: "email is required.",
  ADMIN_NOT_FOUND: "Admin not found.",
  NOT_ACTIVE: "Admin is not active",

  SUB_USER_REGISTER:
    "Have sent the your login id and password to your email, please check.",

  ADMINID_MISSING: "AdminId is missing.",
  ADMIN_DOES_NOT_MATCH: "Admin role does not match.",

  REGISTER_SUCCESS:
    "Register Successfully. Verification Email is sended on registered email, please varify it before login. Thank you!",
  ADMIN_LOGIN: "Admin Login Successfully.",
  LOGOUT_SUCCESS: "Logout Successfully.",
  SUCCESS: "Submit Successfully.",
  UPDATE: "Update Successfully.",
  DELETE: "Delete Successfully.",
  REFERAL_CODE_ALREADY_EXISTS: "Already Use This Code.",
  REFERAL_CODE_NOT_FOUND: "Not Found.",
  ALREADY_CREATED: "This User Already Created Referal Code.",
  INVALID_STATUS: "Invalid approve status.",

  ADMINID_INVALID: "Admin_id is invalid.",
  CONTACT_SUBMITED: "Contact form submitted successfully.",
  SUPER_ADMIN_ALREADY_EXISTS: "Super admin already exists.",

  ACCOUNT_INACTIVE: "Your account is inactive",

  WALLET_OLD_PIN_INVALID: "Invalid old pin.",
  PIN_ALREADY_SET: "Pin already set.",
  WALLET_NOT_FOUND: "Wallet not found.",
  WALLET_PIN_INVALID: "Invalid pin.",

  WALLET_SYNCHRONIZE_PIN_INVALID: "Synchronize pin is required or invalid",
  BRAND_NOT_FOUND: "Brand not found!",
  USER_NOT_VERIFIED: "Not verified user, please verify email!",
  ADDRESS_ADD: "Address Added Successfully",
  ADDRESS_UPDATE: "Address Updated Successfully",
  ADDRESS_DELETE: "Address Deleted Successfully",
  INVALID_ID: "No Data found with this Id",
  GROCERY_CATEGORY_ADD: "Grocery Category Added Successfully",
  NO_CATEGORY: "Grocery category not exist",
  ACCOUNT_DELETED: "Your account has been disabled",

  USER_ACCOUNT:
    "Your account has been deactivated, please activate your account.",
  USER_STATUS: "Change status successfully.",
  ACCOUNT_APPROVED: "Your account is not approved.",

  LINK_NOT_EXISTS: "Link does not exist.",
  LINK_TIME_EXPIRE: "Link expired",
  VERIFY_SUCCESSFULL: "Verify Successfully",
  SOMETHING_WENT_WRONG: "something went wrong",
  ACCOUNT_NOT_APPROVED: "Your account is not approved.",
  EMAIL_NOT_REG: "Email is not registered.",
  PASSWORD_CHANGE_SUUCESSFULL: "Your Password Changed Successfully.",
  DIFFERENT_PWD_NEW_OLD:
    "The new password must be different from old password.",
  LOGIN_FIRST: "please login before update profile!",
  VERSION_CHANGE: "Version Change Successfully.",
  VERSION_ADDED: "Version Added Successfully.",
  COMMENT_ADDED: "Comment Added Successfully.",
  COMMENT_UPDATE: "Comment Updated Successfully.",
  COMMENT_DELETE: "Comment Deleted Successfully.",
  COMMENT_NOT_EXIT: "Comment does not exits.",
  LINK_NOT_EXIT: "Link does not exits.",
  OTP_NOT_VERIFY: "OTP does not verify.",
  MOBILE_IS_NOT_VALID: "Mobile number is not valid",
  EMAIL_ALREDY_USE: "Email already registered",
  CARRIER_NOT_EXITS: "Carrier details not found",
  CARRIER_REJECT_LINK: "Carrier Rejected Link Successfully.",
  REJECT_LINK_HOURS: "You can reject the link once in 24 Hour's.",
  PLEASE_VALID_MOBILE: "Please Enter a valid mobile number.",
  LINK_SEND_SUCCESS: "Link send Successfully.",
  ALL_STATE: "All state saved Successfully.",
  ALL_CITY: "All city saved Successfully.",
  CURRENT_PASSWORD_WRONG: "Your current password is wrong!",
  NEW_PASSWORD_DIFFERENT:
    "New password must be different from previously used password",
  FMCSA_NOT_EXITS: "Fmcsa does not exits.",
  PHONE_BLACK_LIST: "This phone number alredy blacklisted.",
  FACE_BLACK_LIST: "This face AI alredy blacklisted.",
  CARRIER_BLACK_LIST: "This carrier alredy blacklisted.",
  USER_BLACK_LIST: "This user alredy blacklisted.",
  BLACKlIST_ADD_SUUCESSFULL: "Flag added Successfully.",
  BLACKLIST_DELETE_SUUCESSFULL: "Flag Deleted Successfully.",
  BLACKLIST_NOT_EXIT: "Flag does not exits.",
  ALREDDY_SUBMITED_REQUEST: "Alredy Submited request.",
};
